### ISSUE TITLE
Problem with simulation "Output argument "p_t" (and possibly others) not assigned a value in the execution with "BSplineC" function.  Error in PD_control_BSPLINE_demo (line 28) [pt,vt,at,Jt] = BSplineC(P,k,tspan,[3,4,3],0,1);"

### ISSUE THREAD

**Issue by abdul-mannan-khan** [Logan-Shi/UAV-motion-control#1] opened 2023-05-17 19:31 UTC
Hello Logan-Shi, 

Thank you for your research and repository. 

I tried running your code but I am getting following error 

```
Output argument "p_t" (and possibly others) not assigned a value in the execution with "BSplineC" function.

Error in PD_control_BSPLINE_demo (line 28)
[pt,vt,at,Jt] = BSplineC(P,k,tspan,[3,4,3],0,1);
```

Can you please shed some light on it? 

Thank you for your response.

**Comment by Logan-Shi** [comment] 2023-06-07 13:24
Hello Abdul,

There was a minor issue with the "if else" statement. Thank you for noticing. 
I think the issue is fixed now with the latest commits. 

Running "PD_control_BSPLINE_demo.m" should no longer prompt errors after this fix.

**Closed as completed by Logan-Shi** 2023-06-07 13:24 UTC
